config/routes.rb
Rails.application.routes.draw do
  root 'servers#index'

  resources :servers, only: [:index, :show, :destroy] do
    resources :bandwidths, only: [:index, :show, :destroy]
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/bandwidth.rb
class Bandwidth < ApplicationRecord
  belongs_to :server
  # Т.к. скорость интерефейса должна быть больше 0
  validates :value, presence: true, numericality: { greater_than: 0 }
  # Проверка на уникальность имени в пределах сервера
  validates :interface_name, uniqueness: { scope: :server_id }
end

app/models/server.rb
class Server < ApplicationRecord
  has_many :bandwidths, dependent: :destroy

  validates :name, presence: true, uniqueness: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/bandwidths_controller.rb
class BandwidthsController < ApplicationController
  before_action :set_bandwidth, only: %i[show destroy]
  before_action :find_server, only: :index

  # GET /bandwidths or /bandwidths.json
  def index
    @bandwidths = @server.bandwidths
  end

  # GET /bandwidths/1 or /bandwidths/1.json
  def show; end

  # DELETE /bandwidths/1 or /bandwidths/1.json
  def destroy
    @bandwidth.destroy
    respond_to do |format|
      format.html { redirect_to bandwidths_url, notice: 'Bandwidth was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_bandwidth
    @bandwidth = Bandwidth.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def bandwidth_params
    params.require(:bandwidth).permit(:server_id, :value, :interface_name, :value_id)
  end

  def find_server
    @server = Server.find(params[:server_id])
  end
end

app/controllers/servers_controller.rb
class ServersController < ApplicationController
  before_action :set_server, only: %i[show destroy]
  before_action :find_bandwidths, only: %i[show destroy]

  # rescue_from ActiveRecord::RecordNotFound, with: :rescue_with_server_not_found

  # GET /servers or /servers.json
  def index
    @servers = Server.all
    # render json: @servers, status: :ok
  end

  # GET /servers/1 or /servers/1.json
  def show; end

  # DELETE /servers/1 or /servers/1.json
  def destroy
    @server.destroy
    @bandwidths.destroy
    respond_to do |format|
      format.html { redirect_to servers_url, notice: 'Server was successfully destroyed along with it interfaces.' }
      format.json { head :no_content }
    end
    # render json: @server, status: 204
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_server
    @server = Server.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def server_params
    params.require(:server).permit(:name)
  end

  def find_bandwidths
    @bandwidths = @server.bandwidths
  end

  # def rescue_with_server_not_found
  #   render plain: 'Server was not found'
  # end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/bandwidths_helper.rb
module BandwidthsHelper
end

app/helpers/servers_helper.rb
module ServersHelper
end

app/views/bandwidths/_form.html.erb
<%= form_with(model: bandwidth, local: true) do |form| %>
  <% if bandwidth.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(bandwidth.errors.count, "error") %> prohibited this bandwidth from being saved:</h2>

      <ul>
        <% bandwidth.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :server_id %>
    <%= form.text_field :server_id %>
  </div>

  <div class="field">
    <%= form.label :value %>
    <%= form.text_field :value %>
  </div>

  <div class="field">
    <%= form.label :interface_name %>
    <%= form.text_area :interface_name %>
  </div>

  <div class="field">
    <%= form.label :value_id %>
    <%= form.text_field :value_id %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/bandwidths/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Bandwidths</h1>

<table>
  <thead>
    <tr>
      <th>Server</th>
      <th>Value</th>
      <th>Interface name</th>
      <th>Value</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @bandwidths.each do |bandwidth| %>
      <tr>
        <td><%= bandwidth.server_id %></td>
        <td><%= bandwidth.value %></td>
        <td><%= bandwidth.interface_name %></td>
        <td><%= bandwidth.value_id %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

app/views/bandwidths/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Server:</strong>
  <%= @bandwidth.server_id %>
</p>

<p>
  <strong>Value:</strong>
  <%= @bandwidth.value %>
</p>

<p>
  <strong>Interface name:</strong>
  <%= @bandwidth.interface_name %>
</p>

<p>
  <strong>Value:</strong>
  <%= @bandwidth.value_id %>
</p>

<%= link_to 'Back', server_bandwidths_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Task1</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/servers/_form.html.erb
<%= form_with(model: server, local: true) do |form| %>
  <% if server.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(server.errors.count, "error") %> prohibited this server from being saved:</h2>

      <ul>
        <% server.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_area :name %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/servers/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Servers</h1>

<table border=5px width="20%">
  <thead>
    <tr>
      <th>Name</th>
      <th>Action</th>
    </tr>
  </thead>

  <tbody align="center">
    <% @servers.each do |server| %>
      <tr>
        <td><%= link_to server.name, server %></td>
        <td><%= link_to 'Destroy server', server, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

app/views/servers/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Server name:</strong>
  <%= @server.name %>
</p>
<h3>Bandwidths:</h3>

<table border=5px width="20%">
  <thead>
    <tr>
      <th>server_id</th>
      <th>Value</th>
      <th>Interface name</th>
      <th>value_id</th>
    </tr>
  </thead>

  <tbody align="center">
    <% @bandwidths.each do |bandwidth| %>
      <tr>
        <td><%= bandwidth.server_id %></td>
        <td><%= bandwidth.value %> Mbps</td>
        <td><%= bandwidth.interface_name %></td>
        <td><%= bandwidth.value_id %></td>
      </tr>
    <% end %>
  </tbody>
</table>
<br>
<%= link_to 'Back', servers_path %>